import { View, Text } from "@react-pdf/renderer";
import { styles } from "../pdf-styles";

interface ReportFooterProps {
  generatedAt: Date;
}

export function ReportFooter({ generatedAt }: ReportFooterProps) {
  const formattedDateTime = generatedAt.toLocaleString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    timeZoneName: "short",
  });

  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerText}>
        Generated by Galfa Investment Platform - {formattedDateTime}
      </Text>
      <Text
        style={styles.pageNumber}
        render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}`
        }
      />
    </View>
  );
}
